import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { PeriodFilter } from "@/components/period-filter";
import {
  getPeriodRange,
  formatBRL,
  formatPercent,
  STATUS_FUNIL,
  STATUS_LABEL,
  VENDEDORAS,
  relativeFromNow,
  type PeriodKey,
  type PeriodRange,
  type StatusFunil,
} from "@/lib/primor";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Link } from "@tanstack/react-router";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
  LineChart,
  Line,
} from "recharts";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_authenticated/dashboard")({
  component: DashboardPage,
});

function rangeArgs(range: PeriodRange): { p_from: string; p_to: string } {
  // Types generated by Supabase require non-null args; cast null through.
  return {
    p_from: (range.from ? range.from.toISOString() : null) as unknown as string,
    p_to: (range.to ? range.to.toISOString() : null) as unknown as string,
  };
}

function useDashboardData(range: PeriodRange) {
  const args = rangeArgs(range);
  const key = [args.p_from, args.p_to];

  const kpisQ = useQuery({
    queryKey: ["dash-kpis", ...key],
    queryFn: async () => {
      const { data, error } = await supabase.rpc("dashboard_kpis", args);
      if (error) throw error;
      const row = (data?.[0] ?? { total: 0, qualificados: 0, vendidos: 0, faturamento: 0 }) as {
        total: number; qualificados: number; vendidos: number; faturamento: number;
      };
      return row;
    },
  });

  const funilQ = useQuery({
    queryKey: ["dash-funil", ...key],
    queryFn: async () => {
      const { data, error } = await supabase.rpc("dashboard_funil", args);
      if (error) throw error;
      return (data ?? []) as { status_funil: string; qtd: number }[];
    },
  });

  const diaQ = useQuery({
    queryKey: ["dash-dia", ...key],
    queryFn: async () => {
      const { data, error } = await supabase.rpc("dashboard_leads_por_dia", args);
      if (error) throw error;
      return (data ?? []) as { dia: string; qtd: number }[];
    },
  });

  const vendQ = useQuery({
    queryKey: ["dash-vend", ...key],
    queryFn: async () => {
      const { data, error } = await supabase.rpc("dashboard_vendedoras", args);
      if (error) throw error;
      return (data ?? []) as {
        responsavel: string; leads: number; qualificados: number; vendas: number; faturamento: number;
      }[];
    },
  });

  const semInteracaoQ = useQuery({
    queryKey: ["dash-sem-int", ...key],
    queryFn: async () => {
      let q = supabase
        .from("leads")
        .select("id,nome,telefone_e164,responsavel,status_funil,ultima_interacao_em")
        .not("status_funil", "in", "(vendido,perdido)")
        .order("ultima_interacao_em", { ascending: true, nullsFirst: true })
        .limit(8);
      if (range.from) q = q.gte("criado_em", range.from.toISOString());
      if (range.to) q = q.lte("criado_em", range.to.toISOString());
      const { data, error } = await q;
      if (error) throw error;
      return (data ?? []) as {
        id: string; nome: string | null; telefone_e164: string;
        responsavel: string; status_funil: string; ultima_interacao_em: string | null;
      }[];
    },
  });

  return { kpisQ, funilQ, diaQ, vendQ, semInteracaoQ };
}

function DashboardPage() {
  const [period, setPeriod] = useState<PeriodKey>("30d");
  const [custom, setCustom] = useState<PeriodRange>({ from: null, to: null });
  const [vendMetric, setVendMetric] = useState<"leads" | "qualificados" | "vendas" | "faturamento">("leads");
  const range = useMemo(() => getPeriodRange(period, custom), [period, custom]);
  const { kpisQ, funilQ, diaQ, vendQ, semInteracaoQ } = useDashboardData(range);

  const isLoading = kpisQ.isLoading || funilQ.isLoading || diaQ.isLoading || vendQ.isLoading;

  const kpis = useMemo(() => {
    const k = kpisQ.data ?? { total: 0, qualificados: 0, vendidos: 0, faturamento: 0 };
    const total = Number(k.total) || 0;
    const qualificados = Number(k.qualificados) || 0;
    const vendidosCount = Number(k.vendidos) || 0;
    const faturamento = Number(k.faturamento) || 0;
    return {
      total,
      qualificados,
      qualificadosPct: total > 0 ? (qualificados / total) * 100 : 0,
      conversao: total > 0 ? (vendidosCount / total) * 100 : 0,
      faturamento,
      ticketMedio: vendidosCount > 0 ? faturamento / vendidosCount : 0,
      vendidosCount,
    };
  }, [kpisQ.data]);

  const funilData = useMemo(() => {
    const map = new Map((funilQ.data ?? []).map((r) => [r.status_funil, Number(r.qtd) || 0]));
    return STATUS_FUNIL.map((s) => ({ status: STATUS_LABEL[s], qtd: map.get(s) ?? 0 }));
  }, [funilQ.data]);

  const leadsPorDia = useMemo(() => {
    return (diaQ.data ?? []).map((r) => ({
      date: new Date(r.dia + "T00:00:00").toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" }),
      qtd: Number(r.qtd) || 0,
    }));
  }, [diaQ.data]);

  const vendedorasData = useMemo(() => {
    const map = new Map((vendQ.data ?? []).map((r) => [r.responsavel, r]));
    return VENDEDORAS.map((v) => {
      const r = map.get(v);
      return {
        nome: v,
        leads: Number(r?.leads) || 0,
        qualificados: Number(r?.qualificados) || 0,
        vendas: Number(r?.vendas) || 0,
        faturamento: Number(r?.faturamento) || 0,
      };
    });
  }, [vendQ.data]);

  const semInteracao = semInteracaoQ.data ?? [];

  return (
    <div className="p-4 md:p-8 space-y-6 max-w-[1600px] mx-auto">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold">Visão Geral</h1>
          <p className="text-sm text-muted-foreground">
            Acompanhamento do atendimento da IA no WhatsApp
          </p>
        </div>
        <PeriodFilter value={period} onChange={setPeriod} custom={custom} onCustomChange={setCustom} />
      </div>

      {isLoading ? (
        <div className="text-sm text-muted-foreground">Carregando dados...</div>
      ) : (
        <>
          <div className="grid gap-4 grid-cols-2 lg:grid-cols-5">
            <Kpi title="Total de Leads" value={kpis.total.toString()} />
            <Kpi
              title="Qualificados pela IA"
              value={kpis.qualificados.toString()}
              hint={formatPercent(kpis.qualificadosPct)}
            />
            <Kpi title="Conversão" value={formatPercent(kpis.conversao)} hint={`${kpis.vendidosCount} vendas`} />
            <Kpi title="Faturamento" value={formatBRL(kpis.faturamento)} />
            <Kpi title="Ticket Médio" value={formatBRL(kpis.ticketMedio)} />
          </div>

          <div className="grid gap-4 lg:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Funil de leads</CardTitle>
              </CardHeader>
              <CardContent className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={funilData} layout="vertical" margin={{ left: 20 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                    <XAxis type="number" stroke="var(--muted-foreground)" fontSize={12} />
                    <YAxis type="category" dataKey="status" stroke="var(--muted-foreground)" fontSize={12} width={110} />
                    <Tooltip contentStyle={{ background: "var(--card)", border: "1px solid var(--border)" }} />
                    <Bar dataKey="qtd" fill="var(--primary)" radius={[0, 6, 6, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-base">Leads criados por dia</CardTitle>
              </CardHeader>
              <CardContent className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={leadsPorDia}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                    <XAxis dataKey="date" stroke="var(--muted-foreground)" fontSize={12} />
                    <YAxis stroke="var(--muted-foreground)" fontSize={12} allowDecimals={false} />
                    <Tooltip contentStyle={{ background: "var(--card)", border: "1px solid var(--border)" }} />
                    <Line type="monotone" dataKey="qtd" stroke="var(--primary)" strokeWidth={2} dot={{ r: 3 }} />
                  </LineChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader className="flex-row items-center justify-between space-y-0">
              <CardTitle className="text-base">Comparativo entre vendedoras</CardTitle>
              <div className="flex flex-wrap gap-1">
                {(["leads", "qualificados", "vendas", "faturamento"] as const).map((m) => (
                  <Button
                    key={m}
                    size="sm"
                    variant={vendMetric === m ? "default" : "outline"}
                    onClick={() => setVendMetric(m)}
                  >
                    {m === "leads" ? "Leads" : m === "qualificados" ? "Qualificados" : m === "vendas" ? "Vendas" : "Faturamento"}
                  </Button>
                ))}
              </div>
            </CardHeader>
            <CardContent className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={vendedorasData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                  <XAxis dataKey="nome" stroke="var(--muted-foreground)" fontSize={12} />
                  <YAxis stroke="var(--muted-foreground)" fontSize={12} />
                  <Tooltip
                    contentStyle={{ background: "var(--card)", border: "1px solid var(--border)" }}
                    formatter={(v: number) => (vendMetric === "faturamento" ? formatBRL(v) : v)}
                  />
                  <Bar dataKey={vendMetric} fill="var(--primary)" radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-base">Leads sem interação recente</CardTitle>
            </CardHeader>
            <CardContent>
              {semInteracao.length === 0 ? (
                <p className="text-sm text-muted-foreground">Nada por aqui — bom trabalho!</p>
              ) : (
                <ul className="divide-y">
                  {semInteracao.map((l) => (
                    <li key={l.id} className="py-2 flex flex-wrap items-center justify-between gap-2">
                      <div className="min-w-0">
                        <Link
                          to="/leads"
                          search={{ leadId: l.id } as never}
                          className="font-medium hover:underline truncate"
                        >
                          {l.nome || l.telefone_e164}
                        </Link>
                        <div className="text-xs text-muted-foreground">
                          {l.responsavel} · {STATUS_LABEL[l.status_funil as StatusFunil] ?? l.status_funil}
                        </div>
                      </div>
                      <span className="text-xs text-muted-foreground">{relativeFromNow(l.ultima_interacao_em)}</span>
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}

function Kpi({ title, value, hint }: { title: string; value: string; hint?: string }) {
  return (
    <Card>
      <CardContent className="p-4">
        <div className="text-xs uppercase tracking-wide text-muted-foreground">{title}</div>
        <div className="mt-2 text-2xl font-semibold">{value}</div>
        {hint && <div className="mt-1 text-xs text-muted-foreground">{hint}</div>}
      </CardContent>
    </Card>
  );
}
